=begin
#Argo Workflows API

#Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/

OpenAPI spec version: VERSION

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.43

=end

require 'spec_helper'
require 'json'

# Unit tests for argo-workflows::ArtifactServiceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ArtifactServiceApi' do
  before do
    # run before each test
    @instance = argo-workflows::ArtifactServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ArtifactServiceApi' do
    it 'should create an instance of ArtifactServiceApi' do
      expect(@instance).to be_instance_of(argo-workflows::ArtifactServiceApi)
    end
  end

  # unit tests for artifact_service_get_artifact_file
  # Get an artifact.
  # @param namespace 
  # @param id_discriminator 
  # @param id 
  # @param node_id 
  # @param artifact_name 
  # @param artifact_discriminator 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'artifact_service_get_artifact_file test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for artifact_service_get_input_artifact
  # Get an input artifact.
  # @param namespace 
  # @param name 
  # @param node_id 
  # @param artifact_name 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'artifact_service_get_input_artifact test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for artifact_service_get_input_artifact_by_uid
  # Get an input artifact by UID.
  # @param uid 
  # @param node_id 
  # @param artifact_name 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'artifact_service_get_input_artifact_by_uid test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for artifact_service_get_output_artifact
  # Get an output artifact.
  # @param namespace 
  # @param name 
  # @param node_id 
  # @param artifact_name 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'artifact_service_get_output_artifact test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for artifact_service_get_output_artifact_by_uid
  # Get an output artifact by UID.
  # @param uid 
  # @param node_id 
  # @param artifact_name 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'artifact_service_get_output_artifact_by_uid test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
