=begin
#Argo Workflows API

#Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/

OpenAPI spec version: VERSION

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.43

=end

require 'date'

module argo-workflows
  # KafkaTrigger refers to the specification of the Kafka trigger.
  class IoArgoprojEventsV1alpha1KafkaTrigger
    attr_accessor :compress

    attr_accessor :flush_frequency

    # Parameters is the list of parameters that is applied to resolved Kafka trigger object.
    attr_accessor :parameters

    attr_accessor :partition

    # The partitioning key for the messages put on the Kafka topic. +optional.
    attr_accessor :partitioning_key

    # Payload is the list of key-value extracted from an event payload to construct the request payload.
    attr_accessor :payload

    # RequiredAcks used in producer to tell the broker how many replica acknowledgements Defaults to 1 (Only wait for the leader to ack). +optional.
    attr_accessor :required_acks

    attr_accessor :sasl

    attr_accessor :schema_registry

    attr_accessor :tls

    attr_accessor :topic

    # URL of the Kafka broker, multiple URLs separated by comma.
    attr_accessor :url

    attr_accessor :version

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'compress' => :'compress',
        :'flush_frequency' => :'flushFrequency',
        :'parameters' => :'parameters',
        :'partition' => :'partition',
        :'partitioning_key' => :'partitioningKey',
        :'payload' => :'payload',
        :'required_acks' => :'requiredAcks',
        :'sasl' => :'sasl',
        :'schema_registry' => :'schemaRegistry',
        :'tls' => :'tls',
        :'topic' => :'topic',
        :'url' => :'url',
        :'version' => :'version'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'compress' => :'BOOLEAN',
        :'flush_frequency' => :'Integer',
        :'parameters' => :'Array<IoArgoprojEventsV1alpha1TriggerParameter>',
        :'partition' => :'Integer',
        :'partitioning_key' => :'String',
        :'payload' => :'Array<IoArgoprojEventsV1alpha1TriggerParameter>',
        :'required_acks' => :'Integer',
        :'sasl' => :'IoArgoprojEventsV1alpha1SASLConfig',
        :'schema_registry' => :'IoArgoprojEventsV1alpha1SchemaRegistryConfig',
        :'tls' => :'IoArgoprojEventsV1alpha1TLSConfig',
        :'topic' => :'String',
        :'url' => :'String',
        :'version' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'compress')
        self.compress = attributes[:'compress']
      end

      if attributes.has_key?(:'flushFrequency')
        self.flush_frequency = attributes[:'flushFrequency']
      end

      if attributes.has_key?(:'parameters')
        if (value = attributes[:'parameters']).is_a?(Array)
          self.parameters = value
        end
      end

      if attributes.has_key?(:'partition')
        self.partition = attributes[:'partition']
      end

      if attributes.has_key?(:'partitioningKey')
        self.partitioning_key = attributes[:'partitioningKey']
      end

      if attributes.has_key?(:'payload')
        if (value = attributes[:'payload']).is_a?(Array)
          self.payload = value
        end
      end

      if attributes.has_key?(:'requiredAcks')
        self.required_acks = attributes[:'requiredAcks']
      end

      if attributes.has_key?(:'sasl')
        self.sasl = attributes[:'sasl']
      end

      if attributes.has_key?(:'schemaRegistry')
        self.schema_registry = attributes[:'schemaRegistry']
      end

      if attributes.has_key?(:'tls')
        self.tls = attributes[:'tls']
      end

      if attributes.has_key?(:'topic')
        self.topic = attributes[:'topic']
      end

      if attributes.has_key?(:'url')
        self.url = attributes[:'url']
      end

      if attributes.has_key?(:'version')
        self.version = attributes[:'version']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          compress == o.compress &&
          flush_frequency == o.flush_frequency &&
          parameters == o.parameters &&
          partition == o.partition &&
          partitioning_key == o.partitioning_key &&
          payload == o.payload &&
          required_acks == o.required_acks &&
          sasl == o.sasl &&
          schema_registry == o.schema_registry &&
          tls == o.tls &&
          topic == o.topic &&
          url == o.url &&
          version == o.version
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [compress, flush_frequency, parameters, partition, partitioning_key, payload, required_acks, sasl, schema_registry, tls, topic, url, version].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = argo-workflows.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
