=begin
#Argo Workflows API

#Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/

OpenAPI spec version: VERSION

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.43

=end

require 'date'

module ArgoWorkflows
  class IoArgoprojEventsV1alpha1HDFSEventSource
    attr_accessor :addresses

    attr_accessor :check_interval

    attr_accessor :filter

    # HDFSUser is the user to access HDFS file system. It is ignored if either ccache or keytab is used.
    attr_accessor :hdfs_user

    # KrbCCacheSecret is the secret selector for Kerberos ccache Either ccache or keytab can be set to use Kerberos.
    attr_accessor :krb_c_cache_secret

    # KrbConfig is the configmap selector for Kerberos config as string It must be set if either ccache or keytab is used.
    attr_accessor :krb_config_config_map

    # KrbKeytabSecret is the secret selector for Kerberos keytab Either ccache or keytab can be set to use Kerberos.
    attr_accessor :krb_keytab_secret

    # KrbRealm is the Kerberos realm used with Kerberos keytab It must be set if keytab is used.
    attr_accessor :krb_realm

    # KrbServicePrincipalName is the principal name of Kerberos service It must be set if either ccache or keytab is used.
    attr_accessor :krb_service_principal_name

    # KrbUsername is the Kerberos username used with Kerberos keytab It must be set if keytab is used.
    attr_accessor :krb_username

    attr_accessor :metadata

    attr_accessor :type

    attr_accessor :watch_path_config

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'addresses' => :'addresses',
        :'check_interval' => :'checkInterval',
        :'filter' => :'filter',
        :'hdfs_user' => :'hdfsUser',
        :'krb_c_cache_secret' => :'krbCCacheSecret',
        :'krb_config_config_map' => :'krbConfigConfigMap',
        :'krb_keytab_secret' => :'krbKeytabSecret',
        :'krb_realm' => :'krbRealm',
        :'krb_service_principal_name' => :'krbServicePrincipalName',
        :'krb_username' => :'krbUsername',
        :'metadata' => :'metadata',
        :'type' => :'type',
        :'watch_path_config' => :'watchPathConfig'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'addresses' => :'Array<String>',
        :'check_interval' => :'String',
        :'filter' => :'IoArgoprojEventsV1alpha1EventSourceFilter',
        :'hdfs_user' => :'String',
        :'krb_c_cache_secret' => :'IoK8sApiCoreV1SecretKeySelector',
        :'krb_config_config_map' => :'IoK8sApiCoreV1ConfigMapKeySelector',
        :'krb_keytab_secret' => :'IoK8sApiCoreV1SecretKeySelector',
        :'krb_realm' => :'String',
        :'krb_service_principal_name' => :'String',
        :'krb_username' => :'String',
        :'metadata' => :'Hash<String, String>',
        :'type' => :'String',
        :'watch_path_config' => :'IoArgoprojEventsV1alpha1WatchPathConfig'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'addresses')
        if (value = attributes[:'addresses']).is_a?(Array)
          self.addresses = value
        end
      end

      if attributes.has_key?(:'checkInterval')
        self.check_interval = attributes[:'checkInterval']
      end

      if attributes.has_key?(:'filter')
        self.filter = attributes[:'filter']
      end

      if attributes.has_key?(:'hdfsUser')
        self.hdfs_user = attributes[:'hdfsUser']
      end

      if attributes.has_key?(:'krbCCacheSecret')
        self.krb_c_cache_secret = attributes[:'krbCCacheSecret']
      end

      if attributes.has_key?(:'krbConfigConfigMap')
        self.krb_config_config_map = attributes[:'krbConfigConfigMap']
      end

      if attributes.has_key?(:'krbKeytabSecret')
        self.krb_keytab_secret = attributes[:'krbKeytabSecret']
      end

      if attributes.has_key?(:'krbRealm')
        self.krb_realm = attributes[:'krbRealm']
      end

      if attributes.has_key?(:'krbServicePrincipalName')
        self.krb_service_principal_name = attributes[:'krbServicePrincipalName']
      end

      if attributes.has_key?(:'krbUsername')
        self.krb_username = attributes[:'krbUsername']
      end

      if attributes.has_key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      end

      if attributes.has_key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.has_key?(:'watchPathConfig')
        self.watch_path_config = attributes[:'watchPathConfig']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          addresses == o.addresses &&
          check_interval == o.check_interval &&
          filter == o.filter &&
          hdfs_user == o.hdfs_user &&
          krb_c_cache_secret == o.krb_c_cache_secret &&
          krb_config_config_map == o.krb_config_config_map &&
          krb_keytab_secret == o.krb_keytab_secret &&
          krb_realm == o.krb_realm &&
          krb_service_principal_name == o.krb_service_principal_name &&
          krb_username == o.krb_username &&
          metadata == o.metadata &&
          type == o.type &&
          watch_path_config == o.watch_path_config
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [addresses, check_interval, filter, hdfs_user, krb_c_cache_secret, krb_config_config_map, krb_keytab_secret, krb_realm, krb_service_principal_name, krb_username, metadata, type, watch_path_config].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = ArgoWorkflows.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
