=begin
#Argo Workflows API

#Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/

OpenAPI spec version: VERSION

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.43

=end

require 'date'

module ArgoWorkflows
  # PodSecurityContext holds pod-level security attributes and common container settings. Some fields are also present in container.securityContext.  Field values of container.securityContext take precedence over field values of PodSecurityContext.
  class IoK8sApiCoreV1PodSecurityContext
    # appArmorProfile is the AppArmor options to use by the containers in this pod. Note that this field cannot be set when spec.os.name is windows.
    attr_accessor :app_armor_profile

    # A special supplemental group that applies to all containers in a pod. Some volume types allow the Kubelet to change the ownership of that volume to be owned by the pod:  1. The owning GID will be the FSGroup 2. The setgid bit is set (new files created in the volume will be owned by FSGroup) 3. The permission bits are OR'd with rw-rw----  If unset, the Kubelet will not modify the ownership and permissions of any volume. Note that this field cannot be set when spec.os.name is windows.
    attr_accessor :fs_group

    # fsGroupChangePolicy defines behavior of changing ownership and permission of the volume before being exposed inside Pod. This field will only apply to volume types which support fsGroup based ownership(and permissions). It will have no effect on ephemeral volume types such as: secret, configmaps and emptydir. Valid values are \"OnRootMismatch\" and \"Always\". If not specified, \"Always\" is used. Note that this field cannot be set when spec.os.name is windows.
    attr_accessor :fs_group_change_policy

    # The GID to run the entrypoint of the container process. Uses runtime default if unset. May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence for that container. Note that this field cannot be set when spec.os.name is windows.
    attr_accessor :run_as_group

    # Indicates that the container must run as a non-root user. If true, the Kubelet will validate the image at runtime to ensure that it does not run as UID 0 (root) and fail to start the container if it does. If unset or false, no such validation will be performed. May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
    attr_accessor :run_as_non_root

    # The UID to run the entrypoint of the container process. Defaults to user specified in image metadata if unspecified. May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence for that container. Note that this field cannot be set when spec.os.name is windows.
    attr_accessor :run_as_user

    # The SELinux context to be applied to all containers. If unspecified, the container runtime will allocate a random SELinux context for each container.  May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence for that container. Note that this field cannot be set when spec.os.name is windows.
    attr_accessor :se_linux_options

    # The seccomp options to use by the containers in this pod. Note that this field cannot be set when spec.os.name is windows.
    attr_accessor :seccomp_profile

    # A list of groups applied to the first process run in each container, in addition to the container's primary GID and fsGroup (if specified).  If the SupplementalGroupsPolicy feature is enabled, the supplementalGroupsPolicy field determines whether these are in addition to or instead of any group memberships defined in the container image. If unspecified, no additional groups are added, though group memberships defined in the container image may still be used, depending on the supplementalGroupsPolicy field. Note that this field cannot be set when spec.os.name is windows.
    attr_accessor :supplemental_groups

    # Defines how supplemental groups of the first container processes are calculated. Valid values are \"Merge\" and \"Strict\". If not specified, \"Merge\" is used. (Alpha) Using the field requires the SupplementalGroupsPolicy feature gate to be enabled and the container runtime must implement support for this feature. Note that this field cannot be set when spec.os.name is windows.
    attr_accessor :supplemental_groups_policy

    # Sysctls hold a list of namespaced sysctls used for the pod. Pods with unsupported sysctls (by the container runtime) might fail to launch. Note that this field cannot be set when spec.os.name is windows.
    attr_accessor :sysctls

    # The Windows specific settings applied to all containers. If unspecified, the options within a container's SecurityContext will be used. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is linux.
    attr_accessor :windows_options

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'app_armor_profile' => :'appArmorProfile',
        :'fs_group' => :'fsGroup',
        :'fs_group_change_policy' => :'fsGroupChangePolicy',
        :'run_as_group' => :'runAsGroup',
        :'run_as_non_root' => :'runAsNonRoot',
        :'run_as_user' => :'runAsUser',
        :'se_linux_options' => :'seLinuxOptions',
        :'seccomp_profile' => :'seccompProfile',
        :'supplemental_groups' => :'supplementalGroups',
        :'supplemental_groups_policy' => :'supplementalGroupsPolicy',
        :'sysctls' => :'sysctls',
        :'windows_options' => :'windowsOptions'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'app_armor_profile' => :'IoK8sApiCoreV1AppArmorProfile',
        :'fs_group' => :'Integer',
        :'fs_group_change_policy' => :'String',
        :'run_as_group' => :'Integer',
        :'run_as_non_root' => :'BOOLEAN',
        :'run_as_user' => :'Integer',
        :'se_linux_options' => :'IoK8sApiCoreV1SELinuxOptions',
        :'seccomp_profile' => :'IoK8sApiCoreV1SeccompProfile',
        :'supplemental_groups' => :'Array<Integer>',
        :'supplemental_groups_policy' => :'String',
        :'sysctls' => :'Array<IoK8sApiCoreV1Sysctl>',
        :'windows_options' => :'IoK8sApiCoreV1WindowsSecurityContextOptions'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'appArmorProfile')
        self.app_armor_profile = attributes[:'appArmorProfile']
      end

      if attributes.has_key?(:'fsGroup')
        self.fs_group = attributes[:'fsGroup']
      end

      if attributes.has_key?(:'fsGroupChangePolicy')
        self.fs_group_change_policy = attributes[:'fsGroupChangePolicy']
      end

      if attributes.has_key?(:'runAsGroup')
        self.run_as_group = attributes[:'runAsGroup']
      end

      if attributes.has_key?(:'runAsNonRoot')
        self.run_as_non_root = attributes[:'runAsNonRoot']
      end

      if attributes.has_key?(:'runAsUser')
        self.run_as_user = attributes[:'runAsUser']
      end

      if attributes.has_key?(:'seLinuxOptions')
        self.se_linux_options = attributes[:'seLinuxOptions']
      end

      if attributes.has_key?(:'seccompProfile')
        self.seccomp_profile = attributes[:'seccompProfile']
      end

      if attributes.has_key?(:'supplementalGroups')
        if (value = attributes[:'supplementalGroups']).is_a?(Array)
          self.supplemental_groups = value
        end
      end

      if attributes.has_key?(:'supplementalGroupsPolicy')
        self.supplemental_groups_policy = attributes[:'supplementalGroupsPolicy']
      end

      if attributes.has_key?(:'sysctls')
        if (value = attributes[:'sysctls']).is_a?(Array)
          self.sysctls = value
        end
      end

      if attributes.has_key?(:'windowsOptions')
        self.windows_options = attributes[:'windowsOptions']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          app_armor_profile == o.app_armor_profile &&
          fs_group == o.fs_group &&
          fs_group_change_policy == o.fs_group_change_policy &&
          run_as_group == o.run_as_group &&
          run_as_non_root == o.run_as_non_root &&
          run_as_user == o.run_as_user &&
          se_linux_options == o.se_linux_options &&
          seccomp_profile == o.seccomp_profile &&
          supplemental_groups == o.supplemental_groups &&
          supplemental_groups_policy == o.supplemental_groups_policy &&
          sysctls == o.sysctls &&
          windows_options == o.windows_options
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [app_armor_profile, fs_group, fs_group_change_policy, run_as_group, run_as_non_root, run_as_user, se_linux_options, seccomp_profile, supplemental_groups, supplemental_groups_policy, sysctls, windows_options].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = ArgoWorkflows.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
